import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const S=createClient('https://lsuigiuthuycddlcvrds.supabase.co','sb_publishable_kM87waiflFugm53n9o-B4A_mkn5P5Uu');
const ORIGIN='https://pilar-relojes.vercel.app',DEFAULT_IMG='https://lsuigiuthuycddlcvrds.supabase.co/storage/v1/object/public/product-images/87b25917-0e2e-46d1-92ab-f17b25d30d8f/1789530951622-1000503226.webp';
function meta(name,content,property=false){let e=document.head.querySelector(`meta[${property?'property':'name'}="${name}"]`);if(!e){e=document.createElement('meta');e.setAttribute(property?'property':'name',name);document.head.appendChild(e)}e.content=content}
function canonical(url){let e=document.head.querySelector('link[rel="canonical"]');if(!e){e=document.createElement('link');e.rel='canonical';document.head.appendChild(e)}e.href=url}
function jsonld(data){let e=document.getElementById('pilar-seo-jsonld');if(!e){e=document.createElement('script');e.id='pilar-seo-jsonld';e.type='application/ld+json';document.head.appendChild(e)}e.textContent=JSON.stringify(data)}
function apply({title,description,url,image=DEFAULT_IMG,type='website'}){document.title=title;meta('description',description);canonical(url);meta('og:title',title,true);meta('og:description',description,true);meta('og:url',url,true);meta('og:type',type,true);meta('og:image',image,true);meta('og:site_name','PILAR',true);meta('twitter:card','summary_large_image');meta('twitter:title',title);meta('twitter:description',description);meta('twitter:image',image)}
async function run(){if(location.pathname.startsWith('/admin'))return;const path=decodeURI(location.pathname),url=ORIGIN+path;if(path.startsWith('/producto/')){const slug=path.split('/').pop(),{data:p}=await S.from('products').select('id,name,brand,description,price,stock,slug').eq('slug',slug).eq('visible',true).is('deleted_at',null).maybeSingle();if(!p)return;const {data:imgs}=await S.from('product_images').select('public_url,is_primary,sort_order').eq('product_id',p.id).order('is_primary',{ascending:false}).order('sort_order');const image=imgs?.[0]?.public_url||DEFAULT_IMG,description=(p.description||`${p.name} disponible en PILAR, relojería en Sucre, Bolivia.`).slice(0,160),title=`${p.name} | PILAR Relojes Sucre`;apply({title,description,url,image,type:'product'});jsonld({'@context':'https://schema.org','@type':'Product',name:p.name,image:[image],description,sku:p.slug,brand:{'@type':'Brand',name:p.brand||'PILAR'},offers:{'@type':'Offer',url,priceCurrency:'BOB',price:Number(p.price||0),availability:Number(p.stock)>0?'https://schema.org/InStock':'https://schema.org/OutOfStock',itemCondition:'https://schema.org/NewCondition'}});return}const routes={
'/': ['PILAR | Relojes en Sucre Bolivia','Relojes seleccionados en Sucre, Bolivia. Explora modelos PILAR y consulta disponibilidad por WhatsApp.'],
'/catalogo':['Catálogo de relojes | PILAR Sucre','Explora el catálogo de relojes PILAR en Sucre: modelos para varón y dama, novedades y ofertas.'],
'/nuevos':['Nuevos relojes | PILAR Sucre','Descubre los nuevos ingresos de relojes disponibles en PILAR Sucre.'],
'/ofertas':['Relojes en oferta | PILAR Sucre','Encuentra relojes en oferta disponibles en PILAR Sucre y consulta por WhatsApp.'],
'/contacto':['Contacto | PILAR Relojes Sucre','Contacta con PILAR en Sucre para consultar relojes, disponibilidad y delivery.']};const r=routes[path]||routes['/'];apply({title:r[0],description:r[1],url});jsonld({'@context':'https://schema.org','@type':'Store',name:'PILAR',url:ORIGIN,image:DEFAULT_IMG,address:{'@type':'PostalAddress',addressLocality:'Sucre',addressCountry:'BO'}})}
run();
