import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const S=createClient('https://lsuigiuthuycddlcvrds.supabase.co','sb_publishable_kM87waiflFugm53n9o-B4A_mkn5P5Uu');
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const LOGO='https://lsuigiuthuycddlcvrds.supabase.co/storage/v1/object/public/product-images/87b25917-0e2e-46d1-92ab-f17b25d30d8f/1789530951622-1000503226.webp';
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
function brand(){ $$('.brand').forEach(el=>{if(el.dataset.v4Logo)return;el.dataset.v4Logo='1';el.innerHTML=`<img class="pilar-logo-full" src="${LOGO}" alt="PILAR">`;}); }
function home(){if(location.pathname!=='/'&&location.pathname!=='')return; const hero=$('.hero'); if(hero&&!hero.dataset.v4){hero.dataset.v4='1'; hero.querySelector('.heroimg')?.remove(); hero.classList.add('pilar-hero'); const c=hero.firstElementChild; if(c)c.innerHTML=`<div class="hero-kicker">RELOJERÍA · SUCRE, BOLIVIA</div><h1>Tu estilo.<br><span>Tu tiempo.</span></h1><p class="lead">Una selección de relojes pensada para distintos estilos y momentos. Explora la colección y consulta cada modelo directamente por WhatsApp.</p><div class="actions"><a class="btn primary" href="/catalogo">Explorar catálogo</a><a class="hero-link" href="https://wa.me/59175431088" target="_blank">Hablar por WhatsApp →</a></div><div class="hero-meta"><span>Atención 07:00–22:00</span><span>Sucre · Bolivia</span><span>Delivery a consultar</span></div>`;} $$('.benefits,.pilar-trust').forEach(x=>x.remove()); const sec=$$('main .section').find(s=>s.querySelector('.grid')); if(sec){sec.querySelector('.eyebrow')&&(sec.querySelector('.eyebrow').textContent='COLECCIÓN DESTACADA'); const h=sec.querySelector('h2'); if(h)h.innerHTML='Relojes que <em>marcan presencia.</em>';}}
const styleOf=p=>p?.features?.style||p?.features?.estilo||p?.categories?.name||'';
function genderOf(p){const t=norm(`${p?.features?.gender||''} ${p?.features?.genero||''} ${p?.categories?.name||''} ${p?.name||''} ${p?.description||''}`); if(t.includes('mujer')||t.includes('femen'))return'mujer'; if(t.includes('hombre')||t.includes('varon')||t.includes('mascul'))return'hombre'; return'unisex';}
async function catalog(){if(!['/catalogo','/nuevos','/ofertas'].includes(location.pathname))return; const tools=$('.tools'),grid=$('#grid'),cnt=$('#cnt'); if(!tools||!grid||tools.dataset.v4)return; tools.dataset.v4='1'; const {data}=await S.from('products').select('id,name,slug,brand,description,features,is_new,on_sale,visible,deleted_at,categories(name)').eq('visible',true).is('deleted_at',null).order('created_at',{ascending:false}); let items=data||[]; if(location.pathname==='/nuevos')items=items.filter(p=>p.is_new); if(location.pathname==='/ofertas')items=items.filter(p=>p.on_sale); const styles=[...new Set(items.map(styleOf).filter(x=>x&&!['Hombre','Mujer','Unisex'].includes(x)))].sort((a,b)=>a.localeCompare(b,'es')); tools.innerHTML=`<div class="catalog-search"><div class="search-main"><span>⌕</span><input id="pilarSearch" class="input" placeholder="Buscar por marca o estilo"></div><div class="search-options"><label><span>Estilo</span><select id="pilarStyle" class="input"><option value="">Todos</option>${styles.map(x=>`<option>${x}</option>`).join('')}</select></label><label><span>Para</span><select id="pilarGender" class="input"><option value="">Todos</option><option value="hombre">Varón</option><option value="mujer">Mujer</option></select></label></div></div>`; const q=$('#pilarSearch'),s=$('#pilarStyle'),g=$('#pilarGender'); const draw=()=>{const qq=norm(q.value),ss=norm(s.value),gg=g.value; const show=items.filter(p=>{const ps=norm(styleOf(p)), searchable=norm(`${p.brand||''} ${ps}`), pg=genderOf(p); return(!qq||searchable.includes(qq))&&(!ss||ps===ss)&&(!gg||pg===gg||pg==='unisex');}); const allowed=new Set(show.map(p=>p.slug)); $$('.card',grid).forEach(card=>{const href=card.querySelector('a[href^="/producto/"]')?.getAttribute('href')||''; card.hidden=!allowed.has(decodeURIComponent(href.split('/').pop()||''));}); if(cnt)cnt.textContent=`${show.length} reloj${show.length===1?'':'es'} encontrado${show.length===1?'':'s'}`;}; [q,s,g].forEach(x=>x.addEventListener('input',draw)); draw();}
function cards(){ $$('.card').forEach(c=>{c.classList.add('premium-card'); const b=c.querySelector('.cardacts .btn:first-child'); if(b)b.textContent='Ver reloj';}); }
function heading(){if(!['/catalogo','/nuevos','/ofertas'].includes(location.pathname))return; const sec=$('main.section'); if(!sec)return; const e=sec.querySelector(':scope>.eyebrow'),h=sec.querySelector(':scope>h2'); if(e)e.textContent='COLECCIÓN PILAR'; if(h&&location.pathname==='/catalogo')h.innerHTML='Encuentra el reloj<br><em>para tu estilo.</em>';}
function footer(){const f=$('footer'); if(!f||f.dataset.v4)return; f.dataset.v4='1'; f.innerHTML=`<div class="container premium-footer"><div class="footer-brand"><img src="${LOGO}" alt="PILAR"><p>Relojes seleccionados para acompañar tu estilo.</p></div><div><h4>Explorar</h4><a href="/catalogo">Catálogo</a><a href="/nuevos">Nuevos</a><a href="/ofertas">Ofertas</a></div><div><h4>Atención</h4><p>Lunes a domingo<br>07:00–22:00</p><a href="https://wa.me/59175431088" target="_blank">WhatsApp 75431088</a></div><div><h4>Sucre</h4><p>Delivery: consultar por WhatsApp.</p></div></div><div class="footer-meta">© 2026 PILAR · Sucre, Bolivia</div>`;}
function run(){brand();home();heading();cards();footer();catalog();}
new MutationObserver(run).observe(document.body,{childList:true,subtree:true}); run(); setTimeout(run,400); setTimeout(run,1200);