import fs from 'node:fs';import assert from 'node:assert/strict';
const save=fs.readFileSync(new URL('../admin-product-save-v2.js',import.meta.url),'utf8');
assert.match(save,/functions\/v1\/pilar-image-upload/,'Images must use the dedicated Supabase image processor');
assert.match(save,/new FormData/);
assert.match(save,/form\.append\('image'/);
assert.doesNotMatch(save,/PilarImagePro\?\.optimizeFile/);
assert.match(save,/withTimeout\(fetch\(/);
assert.match(save,/const storedPath=reply\.path\|\|path/);
assert.match(save,/failedImages\s*>\s*0/);
console.log('PASS dedicated server image pipeline regression');